### PR TITLE
Generating models

### PR DESCRIPTION
**Pull request by nathansoussana**
Hi @celiahalenke ,

I wrote some validations for each of the core models. I kept it pretty basic mostly with presence validation. Could you please take a look and review?

 I also ran 2 migrations to add a Location to a User and a Description to an Event.

Let me know if you think we should modify, add or remove anything.

Thank you!
Nathan

### CODE REVIEW

**Review by celiahalenke — APPROVED** [review]
Looks good to me!! if we are missing some validations we will realize during coding anyway. this is a great start. Thank you

**Comment by nathansoussana** [comment]
Thank you @celiahalenke ! I'll actually generate the routes and empty controllers in this branch so we can merge it all in one go.

**Comment by nathansoussana** [comment]
@celiahalenke I added the events routes and controller. Please take a look and merge if all good! Thank you

**Comment by nathansoussana** [comment]
Hi @celiahalenke, as I don't see any harm at this stage I'm merging this so that we can start working on the features.

**Pull request merged**
