### PR TITLE
Index backend

### PR DESCRIPTION
**Pull request by nathansoussana**
Hi @MHDNoronha, @celiahalenke,

I seeded the database and further worked on the index page. Could you please review?

Changes:
- Db seeded with 16 sports and 30 events
- Cards in the index page now showing actual data from the db
- Chevrons clickable leading the show page
- Removed avatars from index page to keep it to the essentials

Thank you!
Nathan

Screenshot 2023-06-25 at 13 20 46

### CODE REVIEW

**Review by MHDNoronha — COMMENTED** [review]
image
Looks ans sounds spot on but for some reason the cards are not rendering for me so I just see the banner

**Comment by nathansoussana** [comment]
Hey @MHDNoronha, apologies for the late reply. Maybe bundle install and rails db:migrate would fix it so you can see it on your browser? I used a new gem to populate the database, that could be why.

**Comment by MHDNoronha** [comment]
Hi @nathansoussana, tried both of those ideas, sadly still the same. @celiahalenke if you have had chance to check, does it work for you?

**Comment by MHDNoronha** [comment]
Thanks Nathan, that looks brilliant now!

**Pull request merged**
